### ISSUE TITLE
end-to-end Quick Start > Work Offline fails

### ISSUE THREAD

**Issue by morganrallen** [arc-repos/arc-docs#33]
Following the testing portion of the Offline Guide fails with `Error: socket hung up`.

The tests under `arc.sandbox.http.start` all pass but the next section appears to cause the server to crash.

```
   arc.sandbox.http.start

    @json get /api........................................ get-api
    @html get /........................................... get-index
    ✔ http server started on https://localhost:3333

  get /

/tmp/arcs2/tests/http-test.js:30
    if (err) throw err
             ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by morganrallen** [comment]
In the `get /` test, changing `https` to `http` fixes this.
